-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Restaurantes"
(
    "ID_R" integer NOT NULL,
    "Nome" "char" NOT NULL,
    "Morada" "char" NOT NULL,
    "Email" "char" NOT NULL,
    "Contacto" integer NOT NULL,
    "NIF" integer NOT NULL,
    "Status_Disponibilidade" boolean NOT NULL,
    "Disponibilidade" boolean NOT NULL,
    PRIMARY KEY ("ID_R")
);

CREATE TABLE IF NOT EXISTS public."User"
(
    "ID_User" integer NOT NULL,
    "Username" "char" NOT NULL,
    "Password" "char" NOT NULL,
    "Nome" "char" NOT NULL,
    "Cargo" "char" NOT NULL,
    "Contacto" integer NOT NULL,
    "Morada" "char" NOT NULL,
    "Metodo_Pagamento" "char" NOT NULL,
    "NIF" integer NOT NULL,
    "Data_Nascimento" date NOT NULL,
    PRIMARY KEY ("ID_User")
);

CREATE TABLE IF NOT EXISTS public."Catalogo"
(
    "ID_C" integer NOT NULL,
    "ID_R" integer NOT NULL,
    "Nome_prod" "char" NOT NULL,
    "Tipo" "char" NOT NULL,
    "Preço" double precision NOT NULL,
    "Stock" boolean NOT NULL,
    "C_Detalhes" "char" NOT NULL,
    "Desconto" integer NOT NULL,
    PRIMARY KEY ("ID_C")
);

COMMENT ON COLUMN public."Catalogo"."Tipo"
    IS 'Vegetariano, carne, etc';

CREATE TABLE IF NOT EXISTS public."Pedido"
(
    "ID_P" integer NOT NULL,
    "ID_User" integer NOT NULL,
    "ID_Estafeta" integer NOT NULL,
    "P_Detalhes" "char" NOT NULL,
    "Status" "char" NOT NULL,
    PRIMARY KEY ("ID_P")
);

CREATE TABLE IF NOT EXISTS public."Historico"
(
    "ID_H" integer NOT NULL,
    "ID_User" integer NOT NULL,
    "Data" date NOT NULL,
    "Logs" "char" NOT NULL,
    PRIMARY KEY ("ID_H")
);

CREATE TABLE IF NOT EXISTS public."User_Restaurante"
(
    "ID_User" integer NOT NULL,
    "ID_R" integer NOT NULL,
    "Cargo" "char" NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Publicidade"
(
    "ID_Pub" integer NOT NULL,
    "Nome" "char" NOT NULL,
    "Descricao" "char" NOT NULL,
    "Empresa" "char" NOT NULL,
    PRIMARY KEY ("ID_Pub")
);

CREATE TABLE IF NOT EXISTS public."Metodos de Pagamento"
(
    "ID_M" integer NOT NULL,
    "Nome" "char" NOT NULL,
    PRIMARY KEY ("ID_M")
);

CREATE TABLE IF NOT EXISTS public."Classificações Restaurantes"
(
    "ID_R" integer NOT NULL,
    "ID_User" integer NOT NULL,
    "ID_P" integer NOT NULL,
    "R_Avaliacao" "char",
    "R_Feedback" "char",
    "Data" date
);

CREATE TABLE IF NOT EXISTS public."Classificacao"
(
    "ID_Estafeta" integer NOT NULL,
    "ID_User" integer NOT NULL,
    "ID_P" integer NOT NULL,
    "E_Avaliacao" "char",
    "E_Feedback" "char",
    "Data" date
);

ALTER TABLE IF EXISTS public."Catalogo"
    ADD CONSTRAINT "ID_R_Catalogo_R" FOREIGN KEY ("ID_R")
    REFERENCES public."Restaurantes" ("ID_R") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD FOREIGN KEY ("ID_User")
    REFERENCES public."User" ("ID_User") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Historico"
    ADD FOREIGN KEY ("ID_User")
    REFERENCES public."User" ("ID_User") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_Restaurante"
    ADD CONSTRAINT "ID_R_ID_R" FOREIGN KEY ("ID_User")
    REFERENCES public."User" ("ID_User") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_Restaurante"
    ADD CONSTRAINT "USER_ID" FOREIGN KEY ("ID_R")
    REFERENCES public."Restaurantes" ("ID_R") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Classificações Restaurantes"
    ADD CONSTRAINT "Est" FOREIGN KEY ("ID_R")
    REFERENCES public."Restaurantes" ("ID_R") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Classificações Restaurantes"
    ADD FOREIGN KEY ("ID_User")
    REFERENCES public."User" ("ID_User") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Classificações Restaurantes"
    ADD FOREIGN KEY ("ID_P")
    REFERENCES public."Pedido" ("ID_P") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Classificacao"
    ADD CONSTRAINT "ID_p" FOREIGN KEY ("ID_P")
    REFERENCES public."Pedido" ("ID_P") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Classificacao"
    ADD FOREIGN KEY ("ID_User")
    REFERENCES public."User" ("ID_User") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;